name: Backup Script CI
on: [push]
jobs:
  run-backup:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run backup script 
        run: bash backup-script.sh
